### Super Admin Login
POST /auth/login HTTP/1.1
Host: localhost:8282
Content-Type: application/json

{
  "email": "fsk@gmail.com",
  "password": "123456"
}


### Super Admin ME

GET /users/me HTTP/1.1
Host: localhost:8282
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6IiQyYSQxMCRIci95Z1o1UWduNkhjNXJKUUhCUDFlbmZuNWhrMUs5cHpON1NhMndvQ21TTEdCTkJ3UEg4cSIsImVtYWlsIjoiZnNrQGdtYWlsLmNvbSIsInN1YiI6IlNhaGluIEZ1cmthbiIsImlhdCI6MTcxNDExMTM0MCwiZXhwIjoxNzE0MTE0OTQwfQ.y-jnryNjv3l1ZsujqPElkkZNovH-olJGlYC0zJfB8a0

### Create Admin

POST /admins/ HTTP/1.1
Host: localhost:8282
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6IiQyYSQxMCRIci95Z1o1UWduNkhjNXJKUUhCUDFlbmZuNWhrMUs5cHpON1NhMndvQ21TTEdCTkJ3UEg4cSIsImVtYWlsIjoiZnNrQGdtYWlsLmNvbSIsInN1YiI6IlNhaGluIEZ1cmthbiIsImlhdCI6MTcxNDExMTM0MCwiZXhwIjoxNzE0MTE0OTQwfQ.y-jnryNjv3l1ZsujqPElkkZNovH-olJGlYC0zJfB8a0

{
  "email": "furkankulaksiz@gmail.com",
  "password": "123456",
  "fullName": "Furkan Kulaksız"
}